### ISSUE TITLE
数据库配置是不是错了

### ISSUE THREAD

**Issue by zclcs** [uncarbon97/helio-boot#19]
![image](https://user-images.githubusercontent.com/50291896/198169148-f1eeeb30-bf38-498d-9611-15078fec6cd8.png)

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/198169207-9e06445e-5866-4efe-8f45-0ff237954cd2.png)
![image](https://user-images.githubusercontent.com/50291896/198169233-0eda30a5-3d23-4e44-93db-3637d409a8c8.png)

**Comment by zclcs** [comment]
上面是原配置
![image](https://user-images.githubusercontent.com/50291896/198169962-ef887088-b2bb-4754-b2d5-bc57f16fe36e.png)
改成这样启动成功了

**Comment by uncarbon97** [comment]
https://helio.uncarbon.cc/#/i18n/zh-CN/advanced-usage/multi-tenant?id=%e8%bf%81%e7%a7%bb%e5%88%b0%e6%95%b0%e6%8d%ae%e6%ba%90%e7%ba%a7%e5%a4%9a%e7%a7%9f%e6%88%b7

唔，脚手架默认没有引入多数据源支持
多租户的多数据源配置，我放在了这里
