### ISSUE TITLE
如何给前端返回异常消息

### ISSUE THREAD

**Issue by iguaning** [uncarbon97/helio-boot#34]
业务中throw new BusinessException抛出的异常消息如何返回给前端

**Comment by uncarbon97** [comment]
helio-starter里通过全局异常处理机制，自动确定返回体了哈
具体代码见helio-starter里的：GlobalWebExceptionHandlerAutoConfiguration

**Comment by iguaning** [comment]
正常业务逻辑抛出异常是可以返回的，但是调用线程池在多线程中抛出的异常无法返回给前端，只会在控制台中打印出来，返回给前端的是200，操作成功

**Comment by uncarbon97** [comment]
> 正常业务逻辑抛出异常是可以返回的，但是在线程组中抛出的异常无法返回给前端，只会在控制台中打印出来，返回给前端的是200，操作成功

有代码嘛，可能Web线程和你业务代码执行的线程不是同一个
除非你同步阻塞等待，否则业务代码执行线程的异常不会传递到Web线程，并返回到前端
所以Web线程还是按200返回了

**Comment by iguaning** [comment]
> > 正常业务逻辑抛出异常是可以返回的，但是在线程组中抛出的异常无法返回给前端，只会在控制台中打印出来，返回给前端的是200，操作成功
> 
> 有代码嘛，可能Web线程和你业务代码执行的线程不是同一个 除非你同步阻塞等待，否则业务代码执行线程的异常不会传递到Web线程，并返回到前端 所以Web线程还是按200返回了

代码如下
![微信截图_20240130200825](https://github.com/uncarbon97/helio-boot/assets/27422782/3c251741-1044-4524-b009-2df0b376f50c)
![微信截图_20240130200955](https://github.com/uncarbon97/helio-boot/assets/27422782/49bab2ab-76aa-49c6-b4bb-6c6fcd877b79)
这种情况要如何解决 异常如何传递到web线程

**Comment by uncarbon97** [comment]
> > > 正常业务逻辑抛出异常是可以返回的，但是在线程组中抛出的异常无法返回给前端，只会在控制台中打印出来，返回给前端的是200，操作成功
> > 
> > 
> > 有代码嘛，可能Web线程和你业务代码执行的线程不是同一个 除非你同步阻塞等待，否则业务代码执行线程的异常不会传递到Web线程，并返回到前端 所以Web线程还是按200返回了
> 
> 代码如下 ![微信截图_20240130200825](https://private-user-images.githubusercontent.com/27422782/300799996-3c251741-1044-4524-b009-2df0b376f50c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTc3ODIsIm5iZiI6MTcwNjYxNzQ4MiwicGF0aCI6Ii8yNzQyMjc4Mi8zMDA3OTk5OTYtM2MyNTE3NDEtMTA0NC00NTI0LWIwMDktMmRmMGIzNzZmNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTY2NTEwOGFlNTVkZGU1MzNhNDk2NTVmNGViMDMyYzI5MDNlMmNmZTY0ZjdlNWQ4YTliOTA2YWZjMTgyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BHdQBSAhGaYQHovVoZvv34F7eogg1vCdkG0fYriixN8) ![微信截图_20240130200955](https://private-user-images.githubusercontent.com/27422782/300800017-49bab2ab-76aa-49c6-b4bb-6c6fcd877b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTc3ODIsIm5iZiI6MTcwNjYxNzQ4MiwicGF0aCI6Ii8yNzQyMjc4Mi8zMDA4MDAwMTctNDliYWIyYWItNzZhYS00OWM2LWI0YmItNmM2ZmNkODc3Yjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGZhMWZhYTRhNWNlMjM4MGZkMjYzZTc0ZjI1YzUzMjI2Mjg5YTFhZDZiYmIwNWViYTgzZWY5NTA1YjZjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-UpwWS_anWV_UpQn1A9xAatUzoguUITGoNHMRYgzQc) 这种情况要如何解决 异常如何传递到web线程

这么写的确，Web线程和你业务代码执行的线程不是同一个了
能否checkExistence挪到线程execute之外判断，过了再执行这个异步逻辑

**Comment by uncarbon97** [comment]
或者Service层换成这种写法试试
```java
CompletableFuture<Void> future = CompletableFuture.runAsync(
                () -> SysErrorEnum.INCORRECT_OLD_PASSWORD.assertNotNull(null)
        , 【这里可以指定一个自定义ThreadExecutor】);

        try {
            // 等待 CompletableFuture 完成
            future.get();
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof BusinessException) {
                throw (BusinessException) cause;
            }
            // 处理其他异常情况
        }
```

**Comment by uncarbon97** [comment]
> 或者Service层换成这种写法试试
> 
> ```java
> CompletableFuture<Void> future = CompletableFuture.runAsync(
>                 () -> SysErrorEnum.INCORRECT_OLD_PASSWORD.assertNotNull(null)
>         , 【这里可以指定一个自定义ThreadExecutor】);
> 
>         try {
>             // 等待 CompletableFuture 完成
>             future.get();
>         } catch (ExecutionException e) {
>             Throwable cause = e.getCause();
>             if (cause instanceof BusinessException) {
>                 throw (BusinessException) cause;
>             }
>             // 处理其他异常情况
>         }
> ```

emmm 但是这样本质上还是同步阻塞的了

**Comment by iguaning** [comment]
> > 或者Service层换成这种写法试试
> > ```java
> > CompletableFuture<Void> future = CompletableFuture.runAsync(
> >                 () -> SysErrorEnum.INCORRECT_OLD_PASSWORD.assertNotNull(null)
> >         , 【这里可以指定一个自定义ThreadExecutor】);
> > 
> >         try {
> >             // 等待 CompletableFuture 完成
> >             future.get();
> >         } catch (ExecutionException e) {
> >             Throwable cause = e.getCause();
> >             if (cause instanceof BusinessException) {
> >                 throw (BusinessException) cause;
> >             }
> >             // 处理其他异常情况
> >         }
> > ```
> 
> emmm 但是这样本质上还是同步阻塞的了

这样写就解决了，不过我在想可以在线程组之前获取request线程对象，在线程组子线程中向request线程传递response，思路是这样的但是能力有限没有实现出来。

**Comment by uncarbon97** [comment]
> > > 或者Service层换成这种写法试试
> > > ```java
> > > CompletableFuture<Void> future = CompletableFuture.runAsync(
> > >                 () -> SysErrorEnum.INCORRECT_OLD_PASSWORD.assertNotNull(null)
> > >         , 【这里可以指定一个自定义ThreadExecutor】);
> > > 
> > >         try {
> > >             // 等待 CompletableFuture 完成
> > >             future.get();
> > >         } catch (ExecutionException e) {
> > >             Throwable cause = e.getCause();
> > >             if (cause instanceof BusinessException) {
> > >                 throw (BusinessException) cause;
> > >             }
> > >             // 处理其他异常情况
> > >         }
> > > ```
> > 
> > 
> > emmm 但是这样本质上还是同步阻塞的了
> 
> 这样写就解决了，不过我在想可以在线程组之前获取request线程对象，在线程组子线程中向request线程传递response，思路是这样的但是能力有限没有实现出来。

这么做行不通的哈……按你原来的写法，在web线程启动子线程后，就归还到线程池等待下一个HTTP请求了；子线程中向request线程传递response，可能会污染到其他HTTP请求，也可能request或response对象已失效
