### ISSUE TITLE
求助，项目启动不了

### ISSUE THREAD

**Issue by littlelioncjt** [uncarbon97/helio-boot#35]
java版本1.8.0_73
mvn也执行完成没有红线
![errrrr](https://github.com/uncarbon97/helio-boot/assets/36179203/4d5d0bec-6bf0-47f6-b893-4f6f3e7bfde8)

**Comment by uncarbon97** [comment]
sorry是我的问题，JDK8会有些类文件加载不上，依赖得降级一下

在最外面的大pom，properties节内，加入下面2行
<undertow-core.version>2.2.28.Final</undertow-core.version>
<xnio-api.version>3.8.7.Final</xnio-api.version>

再刷新一下依赖

**Comment by littlelioncjt** [comment]
可以了，谢谢
